### PR TITLE
:)

### PR DESCRIPTION
**Pull request by rainonwires**
theme~!

### CODE REVIEW

**Comment by neauoire** [comment]
Could you add an image to the PR?

**Comment by rainonwires** [comment]
> Could you add an image to the PR?

Erm, what do you mean by this? I know what PR means... but where shall i add an image?
I apologize, bit slow-going tonight.

**Comment by rainonwires** [comment]
rainonwiresthemesmileyfacedotpnglol
heres a look

**Comment by neauoire** [comment]
That's what I meant :)

**Pull request merged**
