### PR TITLE
Proposal for schema change and a couple of trivial enhancements

### PR DESCRIPTION
**Pull request by vaporstack**
Posted this on twitter, idea is to add a minimal meta header to the .thm file to hopefully provide a bit of attribution and future proofing (different versions could be handled differently if need be).

Code modifications are opt in, meaning this should be functionally identical unless the user explicitly enables generation of proposed "v2" schema.

Modified a couple of path.sep in there for windows compat

### CODE REVIEW

**Comment by neauoire** [comment]
Actually, could you remove backward compatibility?
I'll migrate all the apps to this at the same time :)

It's a good PR <3

**Comment by vaporstack** [comment]
Do you mean just leave out the v2 dir and overwrite everything in the existing place? and remove the opt-in?  No prob, but will wait for confirm

**Comment by neauoire** [comment]
Overwrite everything. Everything will use your new format.

**Comment by neauoire** [comment]
Works perfectly, I will migrate the apps as well :)
Thanks a lot!

**Comment by vaporstack** [comment]
Thank you!  Happy to help where I can

**Pull request merged**
