### PR TITLE
so cool

### PR DESCRIPTION
**Pull request by abalone1969**
thanks

### CODE REVIEW

**Comment by neauoire** [comment]
Could you: 
- improve the score
- remove empty lines
- don't use a capital letter in the name

Screenshot from 2019-12-10 07-05-22@2x

**Comment by abalone1969** [comment]
thanks
reading up on style sheets 
this is fun
exit 0

**Comment by abalone1969** [comment]
thank you so much for the lesson
(wait, there's a drag and drop benchmark tester on the themes github page? https://hundredrabbits.github.io/Themes/
wow, that's so cool)
ORCA's fantastic, just stoked to be here, thanks
HipstamaticPhoto-597787248 540106

**Comment by neauoire** [comment]
Nice!

**Pull request merged**
