### PR TITLE
Accidentally nerfed the svg previews (was sending the previous undefined values), fixed now.

### PR DESCRIPTION
**Pull request by vaporstack**

### CODE REVIEW

**Comment by vaporstack** [comment]
The conflicting file is merely a spurious "themes/deuveir" that I accidentally generated somehow, not to be confused with the correct "themes/deuveir.thm" file

**Comment by neauoire** [comment]
I don't know how to resolve conflicts from unmarked PRs!? HALP

**Comment by neauoire** [comment]
Try running `npm start`, I fixed this already I think. I'm using the .data in `index.js`.

**Comment by vaporstack** [comment]
oof I think all you have to do is remove themes/deuveir and should be good

sent from my facsimile machine

**Comment by neauoire** [comment]
I mean, the change you're doing a PR for is already fixed :) is what I mean, stash your changes and try the latest version. It should be working.

**Comment by vaporstack** [comment]
ah cool I was only looking at the data output not the svgs :3 kill it then :)

sent from my facsimile machine

**Pull request closed without merging**
