### PR TITLE
Add contrast warnings to log

### PR DESCRIPTION
**Pull request by jda0**
I've revised the contrast warnings in line with your comments&mdash;warnings inline with a full table in the console&mdash;and integrated 9b84b07.

### CODE REVIEW

**Comment by neauoire** [comment]
perfect <3 Thanks, that works amazingly.

**Comment by neauoire** [comment]
`...` is not valid on safari.

**Comment by jda0** [comment]
which version are you targeting - guessing 9? (should work in 10+)

**Comment by neauoire** [comment]
making a bit of a cleanup, gimme a minute : )

**Pull request merged**
