### PR TITLE
Add Night Owl theme

### PR DESCRIPTION
**Pull request by maxdeviant**
This is a port of [Night Owl](https://github.com/sdras/night-owl-vscode-theme) by @sdras.

### Left

Screen Shot 2019-10-01 at 7 39 14 PM

### Paradise

Screen Shot 2019-10-01 at 7 39 48 PM

### CODE REVIEW

**Comment by neauoire** [comment]
image

**Comment by neauoire** [comment]
Looks great! thank you :)

**Comment by maxdeviant** [comment]
@neauoire Did you mean to merge this PR rather than close it?

**Comment by neauoire** [comment]
*cough* huh of course

**Pull request merged**
